# Task 2: Data Cleaning & Validation

## Step 1: Identifying and Removing Duplicate Rows

In this step, we identify duplicate records in the Shopify dataset.

Duplicate rows can distort sales metrics and lead to incorrect analysis, so they are removed to maintain data integrity.

In [6]:
import pandas as pd

# Load dataset
df = pd.read_csv("../data/Raw_Shopify_Sales.csv")

# Initial shape
print("Initial shape: ", df.shape)

# Preview data
df.head()

Initial shape:  (5680, 38)

,Data Source name,Date,Currency,Sales Channel,Transaction Timestamp,Order Created At,Order Updated At,Order ID,Order Name,Country Funnel,...,Average Order Value (INR),New Customer Orders,Returning Customer Orders,Average Items Per Order,Discounts (INR),Row Count,SKU,Customer Sale Type,Customer ID,Shipping Country
0,Brand A,08-01-2026,INR,Online Store,2026-01-08T11:39:42Z,2026-01-08T11:39:43Z,2026-01-08T11:39:44Z,-6.318230e+12,NaN,United Arab Emirates,...,NaN,0.0,NaN,NaN,0.0,1.0,NaN,First-time,9.052170e+12,NaN
1,Brand A,NAN,INR,Online Store,2026-01-13T06:25:45Z,2026-01-13T06:25:47Z,2026-01-13T06:25:48Z,6.324090e+12,#1053,United States,...,NaN,0.0,NaN,NaN,0.0,1.0,NaN,NaN,9.965681e+14,United States
2,Brand A,19-01-2026,INR,Online Store,2026-01-19T16:16:58Z,2026-01-19T16:16:59Z,2026-01-19T16:17:00Z,6.333300e+12,#1055,United States,...,NaN,0.0,NaN,NaN,NaN,1.0,NaN,First-time,-9.979288e+14,United States
3,Brand A,29-01-2026,INR,Online Store,2026-01-29T15:56:31Z,2026-01-29T15:56:32Z,NaN,6.345630e+12,#1057,United States,...,NaN,0.0,NaN,NaN,0.0,1.0,NaN,First-time,1.000255e+15,United States
4,Brand A,21-01-2026,INR,Online Store,2026-01-21t17:02:56z,2026-01-21T17:02:59Z,2026-01-21T17:03:01Z,6.335680e+12,#1056,India,...,NaN,0.0,NaN,NaN,0.0,NaN,NaN,First-time,NaN,India

In [7]:
duplicate_count = df.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 21

### Detection Method

We used the `.duplicated()` function in pandas to detect rows that are exact duplicates across all columns.

This method flags rows that have identical values across all fields.

In [8]:
df = df.drop_duplicates()

In [9]:
duplicate_count_after = df.duplicated().sum()
print("Duplicates after removal:", duplicate_count_after)

Duplicates after removal: 0

### Result

Duplicate rows were successfully removed, ensuring that each record in the dataset is unique and reliable for further analysis.

## Step 2: Standardizing Date Format

In this step, we convert all date-related columns into proper datetime format.

The dataset contains multiple date columns:
- Date (DD-MM-YYYY format)
- Transaction Timestamp (ISO format)
- Order Created At (ISO format)
- Order Updated At (ISO format)

Since formats are different, we handle them separately.

In [10]:
df.columns

Index(['Data Source name', 'Date', 'Currency', 'Sales Channel',
       'Transaction Timestamp', 'Order Created At', 'Order Updated At',
       'Order ID', 'Order Name', 'Country Funnel', 'Geo Location Segment',
       'Billing Country', 'Billing Province', 'Billing City', 'Order Tags',
       'Product ID', 'Product Title', 'Product Tags', 'Product Type',
       'Variant Title', 'Gross Sales (INR)', 'Net Sales (INR)',
       'Total Sales (INR)', 'Orders', 'Returns (INR)', 'Return Rate',
       'Items Sold', 'Items Returned', 'Average Order Value (INR)',
       'New Customer Orders', 'Returning Customer Orders',
       'Average Items Per Order', 'Discounts (INR)', 'Row Count', 'SKU',
       'Customer Sale Type', 'Customer ID', 'Shipping Country'],
      dtype='object')

In [11]:
df[['Date', 'Transaction Timestamp', 'Order Created At', 'Order Updated At']].head()

,Date,Transaction Timestamp,Order Created At,Order Updated At
0,08-01-2026,2026-01-08T11:39:42Z,2026-01-08T11:39:43Z,2026-01-08T11:39:44Z
1,NAN,2026-01-13T06:25:45Z,2026-01-13T06:25:47Z,2026-01-13T06:25:48Z
2,19-01-2026,2026-01-19T16:16:58Z,2026-01-19T16:16:59Z,2026-01-19T16:17:00Z
3,29-01-2026,2026-01-29T15:56:31Z,2026-01-29T15:56:32Z,NaN
4,21-01-2026,2026-01-21t17:02:56z,2026-01-21T17:02:59Z,2026-01-21T17:03:01Z

### Converting Date Column

The 'Date' column follows DD-MM-YYYY format, so we use `dayfirst=True`.

In [12]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')

df['Date'].head()

0   2026-01-08
1          NaT
2   2026-01-19
3   2026-01-29
4   2026-01-21
Name: Date, dtype: datetime64[ns]

### Converting Timestamp Columns

The remaining columns are already in ISO format (YYYY-MM-DDTHH:MM:SSZ),
so we convert them without using `dayfirst=True`.

In [13]:
timestamp_cols = ['Transaction Timestamp', 'Order Created At', 'Order Updated At']

for col in timestamp_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

df[timestamp_cols].head()

,Transaction Timestamp,Order Created At,Order Updated At
0,2026-01-08 11:39:42+00:00,2026-01-08 11:39:43+00:00,2026-01-08 11:39:44+00:00
1,2026-01-13 06:25:45+00:00,2026-01-13 06:25:47+00:00,2026-01-13 06:25:48+00:00
2,2026-01-19 16:16:58+00:00,2026-01-19 16:16:59+00:00,2026-01-19 16:17:00+00:00
3,2026-01-29 15:56:31+00:00,2026-01-29 15:56:32+00:00,NaT
4,NaT,2026-01-21 17:02:59+00:00,2026-01-21 17:03:01+00:00

### Checking Data Types

We verify that all date columns are successfully converted to datetime format.

In [14]:
df[['Date'] + timestamp_cols].dtypes

Date                          datetime64[ns]
Transaction Timestamp    datetime64[ns, UTC]
Order Created At         datetime64[ns, UTC]
Order Updated At         datetime64[ns, UTC]
dtype: object

### Checking Invalid Dates

We count how many values could not be converted and became NaT.

In [15]:
print("Date nulls:", df['Date'].isnull().sum())

for col in timestamp_cols:
    print(col, "nulls:", df[col].isnull().sum())

Date nulls: 728
Transaction Timestamp nulls: 750
Order Created At nulls: 711
Order Updated At nulls: 732

### Validating Date Logic

We check logical consistency:

- Order Created At should be before or equal to Order Updated At
- Transaction Timestamp should be after Order Created At

Invalid rows are flagged.

In [16]:
df['invalid_order_dates'] = (
    (df['Order Created At'].notnull()) &
    (df['Order Updated At'].notnull()) &
    (df['Order Created At'] > df['Order Updated At'])
)

df['invalid_transaction_time'] = (
    (df['Transaction Timestamp'].notnull()) &
    (df['Order Created At'].notnull()) &
    (df['Transaction Timestamp'] < df['Order Created At'])
)

print("Invalid order dates:", df['invalid_order_dates'].sum())
print("Invalid transaction times:", df['invalid_transaction_time'].sum())

Invalid order dates: 0
Invalid transaction times: 787

## Step 3: Handling Missing Values

In this step, we analyze missing values across the dataset and apply a clear, justified strategy.

Instead of blindly dropping rows, we:
- Identify missing values
- Understand their impact
- Apply appropriate imputation or leave them as is where necessary

In [17]:
df.isnull().sum().sort_values(ascending=False).head(15)

Items Returned               5377
Returning Customer Orders    4016
Average Order Value (INR)    3402
Average Items Per Order      3389
SKU                          3376
Product ID                   2525
Return Rate                  2457
Product Type                 2348
Product Title                2347
Variant Title                2335
Product Tags                 2301
New Customer Orders          1935
Order Tags                   1813
Transaction Timestamp         750
Order Updated At              732
dtype: int64

### Observing Missing Data

We inspect which columns contain missing values and decide strategies based on column importance.

### Strategy for Handling Missing Values

We apply different strategies based on data type and business logic:

1. Date columns → keep NaT (missing dates may be meaningful)
2. Numeric columns → fill with 0 where appropriate (e.g., sales, revenue)
3. Categorical columns → fill with 'Unknown'
4. IDs → do not modify (important identifiers)

In [18]:
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns

numeric_cols

Index(['Order ID', 'Product ID', 'Gross Sales (INR)', 'Net Sales (INR)',
       'Total Sales (INR)', 'Orders', 'Returns (INR)', 'Return Rate',
       'Items Sold', 'Items Returned', 'Average Order Value (INR)',
       'New Customer Orders', 'Returning Customer Orders',
       'Average Items Per Order', 'Discounts (INR)', 'Row Count',
       'Customer ID'],
      dtype='object')

In [19]:
df[numeric_cols] = df[numeric_cols].fillna(0)

### Handling Categorical Columns

Missing categorical values are replaced with 'Unknown' to maintain consistency.

In [20]:
categorical_cols = df.select_dtypes(include=['object']).columns

df[categorical_cols] = df[categorical_cols].fillna('Unknown')

### Keeping Date Columns Unchanged

Date columns are left as NaT because missing dates may indicate incomplete transactions.

In [21]:
df.isnull().sum().sort_values(ascending=False).head(10)

Transaction Timestamp    750
Order Updated At         732
Date                     728
Order Created At         711
Sales Channel              0
Currency                   0
Data Source name           0
Order ID                   0
Order Name                 0
Country Funnel             0
dtype: int64

### Observations

- Numeric values were filled with 0 to avoid calculation issues
- Categorical values were filled with 'Unknown'
- Date columns were preserved as NaT to retain missing information
- This approach ensures minimal data loss while maintaining analytical usability

## Step 4: Recalculating Metrics (CTR, CPC, CPM, ROI)

In this step, we compute key performance metrics from available columns.

Since original metrics are not present in the dataset, we:
- Derive them using source columns
- Identify invalid or unrealistic values

### Note on Metric Availability

The Shopify dataset does not contain required columns such as impressions, clicks, or ad spend.

Therefore:
- CTR (Click Through Rate) cannot be calculated
- CPC (Cost Per Click) cannot be calculated
- CPM (Cost Per 1000 Impressions) cannot be calculated

However, we can calculate ROI using available revenue-related fields.

### Calculating ROI (Return on Investment)

ROI is calculated as:

ROI = (Net Sales - Costs) / Costs

Since cost data is not explicitly available, we approximate using:
- Net Sales (INR)
- Discounts (INR) as a proxy for cost impact

In [22]:
df['ROI_calculated'] = (
    df['Net Sales (INR)'] - df['Discounts (INR)']
) / df['Discounts (INR)']

In [23]:
df['ROI_calculated'] = df['ROI_calculated'].replace([float('inf'), -float('inf')], 0)
df['ROI_calculated'] = df['ROI_calculated'].fillna(0)

### Handling Invalid ROI Values

- Division by zero may produce infinite values
- These are replaced with 0 for stability

In [24]:
df['ROI_flag'] = (df['ROI_calculated'] > 10) | (df['ROI_calculated'] < -1)

### Flagging Suspicious Values

We flag rows where ROI is:
- Extremely high (>10)
- Extremely low (< -1)

These may indicate data quality issues or anomalies.

In [25]:
df['ROI_flag'].sum()

np.int64(62)

In [26]:
df[df['ROI_flag'] == True][
    ['Net Sales (INR)', 'Discounts (INR)', 'ROI_calculated']
].head(10)

      Net Sales (INR)  Discounts (INR)  ROI_calculated
51       8.945902e+05     41803.278705       20.400000
69       8.299441e+05     38782.433295       20.400000
629      3.058060e+06      8820.000000      345.718821
1375    -7.020000e+03       780.000000      -10.000000
1386     8.185500e+05       850.000000      962.000000
1408     1.170000e+04     -1300.000000      -10.000000
1418     3.779000e+02     -3122.100000       -1.121040
1421     2.461000e+05      6200.000000       38.693548
1426     1.412400e+05      7200.000000       18.616667
1429     1.326800e+05      9160.000000       13.484716

## Step 5: Normalising String Columns

In this step, we clean and standardise all string-based columns.

This includes:
- Converting text to consistent format
- Removing extra spaces
- Handling missing values
- Standardising naming conventions

In [27]:
string_cols = df.select_dtypes(include='object').columns
string_cols

Index(['Data Source name', 'Currency', 'Sales Channel', 'Order Name',
       'Country Funnel', 'Geo Location Segment', 'Billing Country',
       'Billing Province', 'Billing City', 'Order Tags', 'Product Title',
       'Product Tags', 'Product Type', 'Variant Title', 'SKU',
       'Customer Sale Type', 'Shipping Country'],
      dtype='object')

### Cleaning Strategy

We apply the following transformations:
- Strip leading/trailing spaces
- Convert text to a consistent format (Title Case)
- Preserve null values correctly

In [28]:
for col in string_cols:
    df[col] = df[col].astype(str).str.strip().str.lower()

df['Data Source name'].head()

0    brand a
1    brand a
2    brand a
3    brand a
4    brand a
Name: Data Source name, dtype: object

In [29]:
for col in string_cols:
    df[col] = df[col].replace(['NAN', 'nan', 'none'], None)

df['Product Tags'].head(20)

0                                                  None
1                                               unknown
2                                               unknown
3                                                  None
4                                               unknown
5                                               unknown
6                                               unknown
7                                               unknown
8                                               unknown
9                                               unknown
10                                              unknown
11                                              unknown
12                                              unknown
13    category_stole, collection_lumiere, tag_newarr...
14                    eoss-25, express shipping, stoles
15           co-ord, eoss-25, floral, linen, top, tunic
16                           eoss-25, shirt, top, tunic
17    co-ord, eoss-25, express shipping, kurta set, ...
18    co-ord, eoss-25, express shipping, kurta set, ...
19    co-ord, eoss-25, express shipping, kurta set, ...
Name: Product Tags, dtype: object

## Step 6: Loading Cleaned Data into SQL

In this step, we load the cleaned Shopify dataset into a SQL database.

We use SQLite for simplicity and consistency with the campaign dataset.

Both datasets will be stored in the same database for downstream analysis.

In [30]:
import sqlite3

In [31]:
conn = sqlite3.connect("../sql/cleaned_shopify.db")

In [32]:
# load dataframe into SQL table
df.to_sql("shopify_sales", conn, if_exists="replace", index=False)

print("Data loaded successfully!")

Data loaded successfully!

In [33]:
# check first few rows
query = "SELECT * FROM shopify_sales LIMIT 5"
pd.read_sql(query, conn)

,Data Source name,Date,Currency,Sales Channel,Transaction Timestamp,Order Created At,Order Updated At,Order ID,Order Name,Country Funnel,...,Discounts (INR),Row Count,SKU,Customer Sale Type,Customer ID,Shipping Country,invalid_order_dates,invalid_transaction_time,ROI_calculated,ROI_flag
0,brand a,2026-01-08 00:00:00,inr,online store,2026-01-08 11:39:42+00:00,2026-01-08 11:39:43+00:00,2026-01-08 11:39:44+00:00,-6.318230e+12,unknown,united arab emirates,...,0.0,1.0,unknown,first-time,9.052170e+12,unknown,0,1,0.0,0
1,brand a,None,inr,online store,2026-01-13 06:25:45+00:00,2026-01-13 06:25:47+00:00,2026-01-13 06:25:48+00:00,6.324090e+12,#1053,united states,...,0.0,1.0,unknown,unknown,9.965681e+14,united states,0,1,0.0,0
2,brand a,2026-01-19 00:00:00,inr,online store,2026-01-19 16:16:58+00:00,2026-01-19 16:16:59+00:00,2026-01-19 16:17:00+00:00,6.333300e+12,#1055,united states,...,0.0,1.0,unknown,first-time,-9.979288e+14,united states,0,1,0.0,0
3,brand a,2026-01-29 00:00:00,inr,online store,2026-01-29 15:56:31+00:00,2026-01-29 15:56:32+00:00,None,6.345630e+12,#1057,united states,...,0.0,1.0,unknown,first-time,1.000255e+15,united states,0,1,0.0,0
4,brand a,2026-01-21 00:00:00,inr,online store,None,2026-01-21 17:02:59+00:00,2026-01-21 17:03:01+00:00,6.335680e+12,#1056,india,...,0.0,0.0,unknown,first-time,0.000000e+00,india,0,0,0.0,0

In [34]:
# list all tables
pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'", conn)

            name
0  shopify_sales

In [35]:
# check number of rows
pd.read_sql("SELECT COUNT(*) as total_rows FROM shopify_sales", conn)

   total_rows
0        5659

In [36]:
df.columns

Index(['Data Source name', 'Date', 'Currency', 'Sales Channel',
       'Transaction Timestamp', 'Order Created At', 'Order Updated At',
       'Order ID', 'Order Name', 'Country Funnel', 'Geo Location Segment',
       'Billing Country', 'Billing Province', 'Billing City', 'Order Tags',
       'Product ID', 'Product Title', 'Product Tags', 'Product Type',
       'Variant Title', 'Gross Sales (INR)', 'Net Sales (INR)',
       'Total Sales (INR)', 'Orders', 'Returns (INR)', 'Return Rate',
       'Items Sold', 'Items Returned', 'Average Order Value (INR)',
       'New Customer Orders', 'Returning Customer Orders',
       'Average Items Per Order', 'Discounts (INR)', 'Row Count', 'SKU',
       'Customer Sale Type', 'Customer ID', 'Shipping Country',
       'invalid_order_dates', 'invalid_transaction_time', 'ROI_calculated',
       'ROI_flag'],
      dtype='object')